export const USER_AUTH_REQUEST = 'USER_AUTH_REQUEST';
export const USER_AUTH_LOGIN = 'USER_AUTH_LOGIN';
export const USER_AUTH_REGISTER = 'USER_AUTH_REGISTER';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_AUTH_LOGOUT = 'USER_AUTH_LOGOUT';
