export const GET_FINANCIERS_LIST_REQUEST = 'GET_FINANCIERS_LIST_REQUEST';
export const GET_FINANCIERS_LIST_SUCCESS = 'GET_FINANCIERS_LIST_SUCCESS';
export const GET_FINANCIERS_LIST_FAIL = 'GET_FINANCIERS_LIST_FAIL';

export const GET_FINANCIER_REQUEST = 'GET_FINANCIER_REQUEST';
export const GET_FINANCIER_SUCCESS = 'GET_FINANCIER_SUCCESS';
export const GET_FINANCIER_FAIL = 'GET_FINANCIER_FAIL';

export const ADD_FINANCIER_REQUEST = 'ADD_FINANCIER_REQUEST';
export const ADD_FINANCIER_SUCCESS = 'ADD_FINANCIER_SUCCESS';
export const ADD_FINANCIER_FAIL = 'ADD_FINANCIER_FAIL';

export const UPDATE_FINANCIER_REQUEST = 'UPDATE_FINANCIER_REQUEST';
export const UPDATE_FINANCIER_SUCCESS = 'UPDATE_FINANCIER_SUCCESS';
export const UPDATE_FINANCIER_FAIL = 'UPDATE_FINANCIER_FAIL';

export const DELETE_FINANCIER_REQUEST = 'DELETE_FINANCIER_REQUEST';
export const DELETE_FINANCIER_SUCCESS = 'DELETE_FINANCIER_SUCCESS';
export const DELETE_FINANCIER_FAIL = 'DELETE_FINANCIER_FAIL';
